<script lang="ts">
	import type { PageData } from './$types';
	import { t, type Lang } from '$lib/i18n';
	let { data }: { data: PageData } = $props();
	const lang = $derived<Lang>(data.lang ?? 'zh');
</script>

<svelte:head><title>{t(lang, 'reports.title')} · Crypto Quant</title></svelte:head>

<main class="mx-auto max-w-7xl px-5 py-8">
	<h1 class="text-2xl font-semibold tracking-tight">{t(lang, 'reports.title')}</h1>
	<p class="mt-1 max-w-3xl text-sm text-muted-foreground">
		{lang === 'en'
			? 'Interactive report bundles generated by scripts/visualize_strategy.py — 7–10 charts per folder (equity curve / drawdown / monthly heatmap / exit reasons …).'
			: '由 scripts/visualize_strategy.py 生成的交互式报告套件 · 每个文件夹 7-10 张图（资金曲线 / 回撤 / 月度热图 / 出场原因…）'}
	</p>

	<div class="mt-6 grid gap-4 md:grid-cols-2">
		{#each data.reports as r}
			<a
				href={`/reports/${r.folder}/`}
				data-sveltekit-reload
				class="group rounded-xl border bg-card p-6 transition-colors hover:border-primary"
			>
				<div class="flex items-baseline justify-between">
					<div class="font-semibold">{r.title}</div>
					<div class="font-mono text-[10px] uppercase text-muted-foreground">
						{r.pages.length} pages
					</div>
				</div>
				<p class="mt-2 text-sm text-muted-foreground">{r.body}</p>
				<div class="mt-3 flex flex-wrap gap-1">
					{#each r.pages.slice(0, 4) as p}
						<span
							class="rounded bg-secondary px-2 py-0.5 text-[10px] font-mono text-secondary-foreground"
						>
							{p.replace('.html', '')}
						</span>
					{/each}
					{#if r.pages.length > 4}
						<span class="text-[10px] text-muted-foreground">+{r.pages.length - 4}</span>
					{/if}
				</div>
				<div class="mt-3 text-xs text-primary opacity-0 transition-opacity group-hover:opacity-100">
					{t(lang, 'common.enter')}
				</div>
			</a>
		{/each}
	</div>

	{#if data.reports.length === 0}
		<div class="mt-8 rounded-lg border border-dashed bg-card p-10 text-center text-muted-foreground">
			{lang === 'en'
				? 'No reports yet. Generate locally with python scripts/visualize_strategy.py; pnpm build will sync them into static/reports/.'
				: '暂无报告。在本地 python scripts/visualize_strategy.py 生成，然后 pnpm build 会自动同步到 static/reports/。'}
		</div>
	{/if}

	{#if data.skipped && data.skipped.length > 0}
		<div class="mt-6 rounded-lg border border-dashed bg-card p-4 text-xs text-muted-foreground">
			⚠️ {lang === 'en'
				? 'The following files exceed Cloudflare Pages’ 25 MB per-file limit and are not live yet:'
				: '以下文件超过 Cloudflare Pages 25 MB 单文件限制，暂未上线：'}
			<ul class="mt-1 list-disc pl-5 font-mono">
				{#each data.skipped as s}
					<li>{s.path} ({s.mb} MB)</li>
				{/each}
			</ul>
			{lang === 'en' ? 'Move to R2 in the future (no size cap).' : '未来可迁到 R2（无 size 限制）。'}
		</div>
	{/if}
</main>
